import type { NextPage } from "next";
import Head from "next/head";

export async function getStaticProps() {
  const res = await fetch("http://localhost:8080/api/users");
  const users = await res.json();

  return {
    props: {
      users,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}

const Users: NextPage = ({ users }) => {
  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>Warehouse App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {users.map((user) => (
        <p>{user.username}</p>
      ))}
    </div>
  );
};

export default Users;
