import type { NextPage } from "next";
import Head from "next/head";

export async function getServerSideProps({ params }) {
  const res = await fetch(
    `http://localhost:8080/api/users/1/warehouses/${params.id}`
  );
  const warehouse = await res.json();
  if (!warehouse) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      warehouse,
    }, // will be passed to the page component as props
  };
}

const Warehouse: NextPage = ({ warehouse }) => {
  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>Warehouse App | {warehouse.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{warehouse.name}</p>
      {warehouse.products.length ? (
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Quatity</th>
              <th>Initial Quantity</th>
              <th>Last Updated</th>
            </tr>
          </thead>
          <tbody>
            {warehouse.products.map((product) => {
              return (
                <tr>
                  <td>{product.name}</td>
                  <td>{product.currentQuantity}</td>
                  <td>{product.initialQuantity}</td>
                  <td>{product.updatedAt}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      ) : (
        <p>No products created for this warehouse</p>
      )}
      <ul></ul>
    </div>
  );
};

export default Warehouse;
