import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

export async function getStaticProps() {
  const res = await fetch("http://localhost:8080/api/users/1/warehouses/");
  const warehouses = await res.json();

  return {
    props: {
      warehouses,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}

const Warehouses: NextPage = ({ warehouses }) => {
  return (
    <div className="bg-gray-100 h-screen">
      <Head>
        <title>Warehouse App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {warehouses.map((warehouse) => (
        <p>
          <Link href={`warehouses/${warehouse.id}`}>{warehouse.name}</Link>
        </p>
      ))}
    </div>
  );
};

export default Warehouses;
